services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-call-app-dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=4000
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: ai-call-nginx-dev
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    restart: unless-stopped
