version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-call-app
    environment:
      - NODE_ENV=production
      - PORT=3000
    expose:
      - "3000"
    depends_on:
      - db
    restart: unless-stopped

  media:
    build:
      context: .
      dockerfile: media-engine/Dockerfile
    container_name: ai-call-media
    environment:
      - HOST=0.0.0.0
      - PORT=7000
    expose:
      - "7000"
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    container_name: ai-call-postgres
    environment:
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
      - POSTGRES_DB=aicall
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: ai-call-bot
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://ai:ai@db:5432/aicall
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    container_name: ai-call-nginx
    depends_on:
      - app
      - media
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/usr/share/nginx/html:ro
    restart: unless-stopped

volumes:
  pgdata:
